# Writes the revisions a build is compiled from into a header (ABT #1588 / #1592). Run as a
# script on EVERY build (not once at configure): a revision captured at configure time goes
# stale the moment someone commits and rebuilds without re-configuring, which is the same wrong
# record this replaces. configure_file only rewrites the header when a value changed, so an
# unchanged tree does not recompile anything.
#
#   cmake -DOUT=<header> -DMVBPP_DIR=<src> -DMKF_DIR=<src> -DMAS_DIR=<src> -P BuildRev.cmake
#
# A tree with uncommitted changes to tracked files is reported with a "-dirty" suffix: in a
# shared checkout the HEAD SHA alone does not say what was compiled. A directory that is not a
# git checkout stops the build -- a revision record that can be wrong is worse than none.
function(_rev dir out)
    # Remaining arguments: pathspecs to leave out of the dirty test -- only the edits this
    # build itself makes to a dependency checkout (MKF: its CMakeLists SHARED->STATIC patch and
    # the MAS symlink that replaces its submodule), never anything a person could have changed.
    set(_excl "")
    foreach(_p ${ARGN})
        list(APPEND _excl ":(exclude)${_p}")
    endforeach()
    execute_process(COMMAND git -C "${dir}" rev-parse HEAD
                    OUTPUT_VARIABLE sha OUTPUT_STRIP_TRAILING_WHITESPACE
                    RESULT_VARIABLE rc ERROR_QUIET)
    if(NOT rc EQUAL 0 OR sha STREQUAL "")
        message(FATAL_ERROR "BuildRev: ${dir} is not a git checkout; cannot record what this build is compiled from")
    endif()
    execute_process(COMMAND git -C "${dir}" status --porcelain --untracked-files=no -- . ${_excl}
                    OUTPUT_VARIABLE st OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE rc2)
    if(NOT rc2 EQUAL 0)
        message(FATAL_ERROR "BuildRev: git status failed in ${dir}")
    endif()
    if(NOT st STREQUAL "")
        set(sha "${sha}-dirty")
    endif()
    set(${out} "${sha}" PARENT_SCOPE)
endfunction()

_rev("${MVBPP_DIR}" MVBPP_REV)
_rev("${MKF_DIR}" MKF_REV CMakeLists.txt MAS)
_rev("${MAS_DIR}" MAS_REV)
file(WRITE "${OUT}.tmp"
"#pragma once\n// Generated by cmake/BuildRev.cmake on every build. Do not edit.\n"
"#define MVBPP_BUILD_REV_MVBPP \"${MVBPP_REV}\"\n"
"#define MVBPP_BUILD_REV_MKF \"${MKF_REV}\"\n"
"#define MVBPP_BUILD_REV_MAS \"${MAS_REV}\"\n")
configure_file("${OUT}.tmp" "${OUT}" COPYONLY)
file(REMOVE "${OUT}.tmp")
